### ISSUE TITLE
Error Notice

### ISSUE THREAD

**Issue by GreenixMKTG** [lukecav/performance-improvements-for-woocommerce#1]
I am seeing this notice:
wp_deregister_style was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. Please see Debugging in WordPress for more information. (This message was added in version 3.3.0.)

wp_deregister_style()
wp-content/plugins/performance-improvements-for-woocommerce-master/wc-performance-improvements.php:81
_wp_scripts_maybe_doing_it_wrong()
wp-includes/functions.wp-styles.php:141
wp-includes/functions.php:4773

Anything  I need to worry about or need to fix?

Thanks!!

**Comment by lukecav** [comment]
https://github.com/lukecav/performance-improvements-for-woocommerce/blob/master/wc-performance-improvements.php#L55-L57
