### ISSUE TITLE
FYI, you can add another filter

### ISSUE THREAD

**Issue by patrick-leb** [lukecav/performance-improvements-for-woocommerce#12]
`woocommerce_admin_payment_gateway_suggestion_specs` is the one that pollutes the payment settings:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/68301566/211593421-f3944950-2ac8-4d6e-a9b8-18a4845845ab.png">

`add_filter('woocommerce_admin_payment_gateway_suggestion_specs',  '__return_empty_array');`

**Comment by lukecav** [comment]
K done.
https://github.com/lukecav/performance-improvements-for-woocommerce/releases/tag/v1.1.17
