### ISSUE TITLE
Submit To WordPress.org

### ISSUE THREAD

**Issue by varunsridharan** [lukecav/performance-improvements-for-woocommerce#3]
Hi There

Thanks for creating a great plugin to speed up the website

i think it would be great if you could submit this to wordpress.org 

so end developers like me can update it more easily

**Comment by lukecav** [comment]
Yep might be worth a shot.

**Comment by lukecav** [comment]
The best option at the moment is going to be.
https://github.com/lukecav/performance-improvements-for-woocommerce/blob/main/README.md#automatic-updates
https://github.com/afragen/github-updater
