### ISSUE TITLE
Please add a composer.json file

### ISSUE THREAD

**Issue by rfair404** [lukecav/performance-improvements-for-woocommerce#6]
@lukecav we use this plugin on all of our shops (thank you for your work). We are moving our setup to a composer based installation, and as this plugin isn't in the wp.org repos, it is not available via wpackagist.org either. As an alternative, I would suggest that you add a `composer.json` file so that this plugin can be installed via composer. Please see #5

**Comment by lukecav** [comment]
Yep sure let me see what I can do.

**Comment by lukecav** [comment]
Looks like you already added the PR for it. https://github.com/lukecav/performance-improvements-for-woocommerce/pull/5
